/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  blog: [{
    type: 'category',
    label: 'blog',
    items: [{
      type: 'doc',
      label: '如何使用tana的part of功能实现语义化层级查询',
      id: 'how-to-use-tana-part-of',
    }]
  }],
};

module.exports = sidebars;
